# Generated by Django 5.0.7 on 2024-07-25 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='bonk/static/')),
                ('brand', models.CharField(max_length=50)),
                ('power', models.CharField(max_length=50)),
                ('sold_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('AMR', 'ASTON MARTIN'), ('BMW', 'BAYES MOTOR WORKS'), ('AMG', 'MERCEDES AMG'), ('BNZ', 'MERCEDES BENZ'), ('BGT', 'BUGGATI'), ('POR', 'PORSCHE')], max_length=3)),
            ],
        ),
    ]
