# Generated by Django 5.0.7 on 2024-07-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartype',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cartype',
            name='nationality',
            field=models.TextField(default='unavailable'),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='type',
            field=models.CharField(choices=[('ETT', 'Extreme Track Toys'), ('TT_', 'Track Toys'), ('OR_', 'Off Road'), ('EOR', 'Extreme Off Road'), ('GT_', 'GT'), ('SGT', 'Super GT'), ('DFT', 'Drift')], max_length=3),
        ),
    ]
