# Generated by Django 5.0.7 on 2024-07-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonk', '0002_cartype_description_cartype_nationality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
            ],
        ),
    ]
