# Generated by Django 5.0.7 on 2024-07-28 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonk', '0003_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
